name: CI

on:
  push:
    branches:
      - main
      - '**'    # optional: match all branches
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage codecov pytest pytest-asyncio

      - name: Patch graphorchestrator/core/state.py
        run: |
          echo 'print("hello world")' >> graphorchestrator/core/state.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and Push Patched File
        run: |
          git add graphorchestrator/core/state.py
          git commit -m "Patch: Add hello world print to state.py"
          git push origin HEAD:${{ github.head_ref }}

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=85
          coverage xml  # Generate XML for Codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: pytest
          name: python-coverage
          fail_ci_if_error: true
