name: Count Lines of Code (CLOC)

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-cloc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Run cloc
        run: |
          cloc . > cloc-report.txt
          cat cloc-report.txt

      - name: Upload cloc report
        uses: actions/upload-artifact@v3
        with:
          name: cloc-report
          path: cloc-report.txt
